### ISSUE TITLE
Styles conflicts 

### ISSUE THREAD

**Issue by DenissKulakov** [creativetimofficial/material-dashboard-angular2#4]
I have some troubles with implementing dashboard with your material ui kit. There is problems in navbar. When am using material-dashboard.css it broke the standart navbar settings from material ui kit. (I am using angular 2).

For example i have two components: Component "A" where is classic landing page from material uit kit package, using material-kit.css in styleurls property. Everything is work well. 

Then, component "B" (with multiplie components inside like in example navbar,footer,sidebar and js files also included like in example) uses material-dashboard.css in styleurls property. Here navbar brakes down when i change size of window, collapse dont work and burger button does not show menu on right side. 
**But if i include material-dashboard.css to index page, it works well, as in example.** And here problem begins - navbar in component A brakes down(burger button does not work), **because styles from material-dashboard.css overrides navbar styles from material-kit.css**. I dont know why material-dashboard.css styles (navbar styles) dont work when i include them into separate components (component B and his child components). It works only when i got in index page, but then i got problems with classic navbar from material ui kit. 

**The question is how i can implement this "dashboard navbar" from material dashboard with "classic navabar" from material ui kit? Is it real?** I have spend around 4-5 days on this problem and always getting that some parts brakes down. I really enjoy your style and would like to purchase. Hope to receive some help or explanation. 

I am trying to find some workaround/hack to use material-kit.css for some pages (landing login etc) and styles from material-dashboard.css for admin panel component. I s there a way to dynamically (based on root) change/(add or remove) css file in index page. 

P.s. Material-kit.css from material kit work very well if i put them only in component styleurls property).

**Comment by alexandru-paduraru** [comment]
@DenissKulakov thank you for using our products and sorry for the late response. I can say before writing a detailed explanation that you shouldn't combine both CSSs because they are not 100% compatible. We've seen requests for the compatibility and we will see if this will be something that we will implement in the future.

The basic idea is that you should keep the products' CSS files separate and not try to combine them because you will load your page with too much CSS and Javascript which are not necessary in the same time. Your user will be either on a Landing Page, or on the Admin Part. If you like for example 1 item from one product, like a Card, and it is not in the other product, you can check in the next example how to do that using the SCSS files.

Just follow the next steps, for the FileUpload Example:

1. You can got to material-kit/assets/sass/material-kit/_fileupload.scss and put it in the same folder structure to material-dashboard.
2. Compile again the assets/sass/material-dashboard.scss SASS using Koala http://koala-app.com/ (make sure you set the output path to assets/css/material-kit.css).
3. Move the library for the file upload from material-kit/assets/js/jasny-bootstrap.min.js to the same folder in material-dashboard and then everything should work fine in the Dashboard.

What we recommend you is to have some kind of 2 layouts, 1 layout for the Dashboard and 1 layout for the pages which use Material Kit. We didn't know how to do the layouts issue because we wanted a different layout for the Login/Register/Lock page and we just made them static HTML pages...but I know this is a temporary solution.

Did you check this: http://stackoverflow.com/questions/33328347/angular2-dynamic-change-css-property?

Can you share your project with us? We will have a look and see if we can find a workaround for the navbar case.

Best,
Alex

**Comment by elvnthaus** [comment]
I'm having the same issue. Is a fix in the process?
